// Algerian cities — coordinates, maps, and detailed travel highlights.
export const CITIES = [
  {
    city: "ALGIERS",
    arabic: "الجزائر",
    landmark: "CASBAH",
    region: "NORTH",
    wilaya: "Algiers Province",
    lat: 36.7538,
    lng: 3.0588,
    coords: "36°45′N · 3°03′E",
    tags: ["UNESCO", "MEDINA", "CAPITAL"],
    description:
      "The Casbah crowns the bay of Algiers — a labyrinth of whitewashed alleys, Ottoman palaces, and mosques cascading toward the Mediterranean. Algeria's capital blends French colonial boulevards with a living UNESCO medina at its heart.",
    art: "casbah",
    colors: ["#f5f0e6", "#c4b8a8", "#1a3d5c"],
    highlights: [
      { title: "The Casbah (Kasbah)", text: "UNESCO-listed medina with Ottoman palaces, mosques, and winding stairways overlooking the bay." },
      { title: "Notre Dame d'Afrique", text: "Neo-Byzantine basilica on a cliff with sweeping views over the city and sea." },
      { title: "Martyrs' Memorial (Maqam Echahid)", text: "Iconic concrete monument honouring the War of Independence, with a museum beneath." },
      { title: "Bab El Oued & the corniche", text: "Vibrant waterfront neighbourhoods where street life meets the Mediterranean breeze." },
      { title: "Bardo Museum of Prehistory", text: "Housed in a Ottoman villa — fossils, rock art casts, and early human artefacts from the Sahara." },
      { title: "Jardin d'Essai du Hamma", text: "A 58-hectare botanical garden planted in 1832 — palms, fountains, and shaded alleys." },
      { title: "Palais des Rais (Bastion 23)", text: "Restored Ottoman palace complex on the lower Casbah — courtyards, tiles, and sea glimpses." },
      { title: "Street food & coffee culture", text: "Mahjouba, chorba, and mint tea in cafés along Didouche Mourad and the Casbah lanes." },
      { title: "Dar Hassan Pacha", text: "One of the grandest Ottoman residences — intricate stucco and painted cedar ceilings." },
      { title: "Sunset from the Casbah ramparts", text: "Watch the bay turn gold as the call to prayer echoes across the white-washed rooftops." },
    ],
  },
  {
    city: "CONSTANTINE",
    arabic: "قسنطينة",
    landmark: "SIDI M'CID BRIDGE",
    region: "EAST",
    wilaya: "Constantine Province",
    lat: 36.365,
    lng: 6.6147,
    coords: "36°22′N · 6°37′E",
    tags: ["BRIDGE", "GORGES", "CULTURE"],
    description:
      "Constantine — the City of Bridges — is carved by the Rhumel gorge. Suspended footbridges, Ottoman palaces, and a proud Cirta heritage make it one of North Africa's most dramatic urban landscapes.",
    art: "bridge",
    colors: ["#8ec5e8", "#2d6a9f", "#0a1a28"],
    highlights: [
      { title: "Sidi M'Cid Bridge", text: "175 m above the gorge — Gustave Eiffel's influence, dizzying views, and the city's emblem." },
      { title: "Palais Ahmed Bey", text: "Ottoman-era palace with Andalusian courtyards, now a cultural centre." },
      { title: "Emir Abdelkader Mosque", text: "One of the largest mosques in Algeria — soaring minarets visible from every bridge." },
      { title: "Cirta Museum", text: "Roman mosaics, Punic artefacts, and the story of ancient Cirta beneath modern Constantine." },
      { title: "Salah Bey Bridge & Mellah Slimane Bridge", text: "Walk the network of bridges linking the plateau neighbourhoods across the void." },
      { title: "Soumma Canyon viewpoints", text: "Deep gorges cut through limestone — best appreciated at dawn from the plateau edge." },
      { title: "Old town medina", text: "Narrow lanes, artisan workshops, and traditional Constantine pastries." },
      { title: "Gustave Mercier Museum", text: "Fine arts collection in a historic villa — Algerian painters and temporary exhibitions." },
      { title: "El Kantara Bridge", text: "The oldest bridge in the city — Roman foundations, rebuilt through the centuries." },
      { title: "Kabyle & Chaoui influences", text: "Markets brim with mountain honey, handmade textiles, and eastern highland crafts." },
    ],
  },
  {
    city: "ORAN",
    arabic: "وهران",
    landmark: "SANTA CRUZ",
    region: "WEST",
    wilaya: "Oran Province",
    lat: 35.6969,
    lng: -0.6331,
    coords: "35°42′N · 0°38′W",
    tags: ["BAY", "MUSIC", "FORT"],
    description:
      "Oran is Algeria's radiant west-coast port — raï music, Spanish echoes, and the fortress of Santa Cruz watching over one of the Mediterranean's great bays.",
    art: "fort",
    colors: ["#ffd166", "#ef476f", "#073b4c"],
    highlights: [
      { title: "Santa Cruz Fort & chapel", text: "Climb Murdjadjo hill for panoramic views, a whitewashed chapel, and the bay below." },
      { title: "Ahmed Zabana National Museum", text: "Archaeology, colonial history, and Oran's role as a cultural crossroads." },
      { title: "Bey's Palace (Palais du Bey)", text: "Ottoman residence turned museum — ornate interiors in the old medina." },
      { title: "Seafront promenade", text: "Kilometres of corniche, cafés, and evening strolls along the Mediterranean." },
      { title: "Raï music heritage", text: "Birthplace of Cheb Khaled and the raï revolution — clubs and festivals year-round." },
      { title: "Great Synagogue of Oran", text: "Striking Moorish-revival architecture recalling the city's diverse past." },
      { title: "Mers El Kébir & Cap Falcon", text: "Dramatic headlands west of the city — cliffs, fortifications, and open sea." },
      { title: "Saint-Louis quarter", text: "Spanish-era streets, arcades, and the flavour of old Oran." },
      { title: "Marché Medina Jedida", text: "Spices, olives, fresh fish, and the bustle of a working port city." },
      { title: "Sunset from the fort", text: "The bay ignites at dusk — fishing boats, minarets, and the Atlas foothills beyond." },
    ],
  },
  {
    city: "GHARDAÏA",
    arabic: "غرداية",
    landmark: "MZAB VALLEY",
    region: "SAHARA",
    wilaya: "Ghardaïa Province",
    lat: 32.4902,
    lng: 3.673,
    coords: "32°29′N · 3°40′E",
    tags: ["UNESCO", "OASIS", "MOZABITE"],
    description:
      "In the M'zab Valley, five fortified ksour rise from the desert — a UNESCO masterpiece of Mozabite urban planning, where cubic homes and minarets glow amber at sunset.",
    art: "ksar",
    colors: ["#e8a838", "#c45c26", "#2d1810"],
    highlights: [
      { title: "Ghardaïa ksar (Taghardait)", text: "The main fortified town — cubic architecture, covered alleys, and a skyline of minarets." },
      { title: "Beni Isguen", text: "The most preserved ksar — strict traditions, white-painted walls, and a timeless atmosphere." },
      { title: "Melika, Bounoura & El Atteuf", text: "Four sister towns completing the pentapolis — each with its own market and mosque." },
      { title: "Mozabite market (souq)", text: "Dates, silver jewellery, woven carpets, and the famous Ghardaïa burnous." },
      { title: "M'zab Valley UNESCO site", text: "A 7th-century urban model adapted to the desert — studied by architects worldwide." },
      { title: "Palm groves & irrigation", text: "Walk the foggaras (ancient channels) feeding thousands of palms in the oasis." },
      { title: "Traditional cuisine", text: "Couscous, medfouna (Berber pizza), and sweet deglet nour dates." },
      { title: "Sunset from the ksar roof", text: "The valley turns copper-gold as shadows climb the cuboid houses." },
      { title: "Craft workshops", text: "Watch silversmiths and textile weavers in family ateliers." },
      { title: "Desert excursions", text: "Day trips into the northern Sahara — dunes, nomad tea, and infinite horizons." },
    ],
  },
  {
    city: "TIPAZA",
    arabic: "تيبازة",
    landmark: "ROMAN RUINS",
    region: "NORTH",
    wilaya: "Tipaza Province",
    lat: 36.5897,
    lng: 2.4474,
    coords: "36°35′N · 2°27′E",
    tags: ["ROMAN", "COAST", "UNESCO"],
    description:
      "Where the Mediterranean kisses ancient stone, Tipaza's Roman theatre and temples overlook turquoise waters. Cicero called it 'a little Rome' — ruins framed by cypress, wildflowers, and sea.",
    art: "roman",
    colors: ["#a8dadc", "#457b9d", "#1d3557"],
    highlights: [
      { title: "Tipaza Archaeological Park", text: "UNESCO Roman ruins — theatre, basilica, forum, and mosaics metres from the shore." },
      { title: "Royal Mausoleum of Mauretania", text: "The Kbor er Roubia — a 21 m stone tomb on a hill, possibly Cleopatra Selene's resting place." },
      { title: "Museum of Tipaza", text: "Sculptures, inscriptions, and mosaics from the Punic and Roman periods." },
      { title: "Chenoua Cape", text: "Rocky peninsula with beaches, pine woods, and views back to the ruins." },
      { title: "Fresh seafood restaurants", text: "Grilled fish and chorba by the water after exploring the site." },
      { title: "Punic-Roman harbour remains", text: "Ancient quays still trace the curve of the bay." },
      { title: "Birdwatching", text: "Migratory species rest on the coast — especially in spring and autumn." },
      { title: "Cherchell (Caesarea)", text: "A short drive west — another major Roman city with a superb archaeological museum." },
      { title: "Coastal hiking", text: "Trails along the cliffs linking beaches, coves, and Roman fragments." },
      { title: "Sunset among the columns", text: "The ruins silhouette against the sea — one of Algeria's most poetic evenings." },
    ],
  },
  {
    city: "TAMANRASSET",
    arabic: "تمنراست",
    landmark: "HOGGAR MOUNTAINS",
    region: "DEEP SOUTH",
    wilaya: "Tamanrasset Province",
    lat: 22.785,
    lng: 5.5228,
    coords: "22°47′N · 5°31′E",
    tags: ["TUAREG", "DESERT", "ASSEKREM"],
    description:
      "Gateway to the Hoggar, Tamanrasset opens onto volcanic peaks and endless dunes. From Assekrem, the sunrise over the Sahara ranks among the most sublime views on the African continent.",
    art: "hoggar",
    colors: ["#ff6b35", "#4a1942", "#1a0a2e"],
    highlights: [
      { title: "Assekrem plateau", text: "Charles de Foucauld's hermitage — 360° sunrise views over volcanic peaks and desert." },
      { title: "Tahat summit (2,908 m)", text: "Highest peak in the Hoggar — multi-day treks for experienced hikers." },
      { title: "Tuareg culture & markets", text: "Indigo turbans, silver crosses of Agadez, leather work, and desert hospitality." },
      { title: "Hoggar National Park", text: "Basalt formations, gueltas (desert pools), and acacia valleys." },
      { title: "Djanet road & Tassili access", text: "The legendary desert highway — expeditions south into rock-art country." },
      { title: "Camel trekking", text: "Multi-day nomad-led journeys between wells and sand seas." },
      { title: "Night skies", text: "Zero light pollution — the Milky Way arches over the camp each night." },
      { title: "Traditional touareg music", text: "Imzad violin and tende drum performances in the oasis town." },
      { title: "In Salah & erg landscapes", text: "Day trips to red sand dunes and fossil fields." },
      { title: "Desert gardens", text: "Irrigated pockets of palms and vegetables in an otherwise arid world." },
    ],
  },
  {
    city: "DJANET",
    arabic: "جانت",
    landmark: "TASSILI N'AJJER",
    region: "DEEP SOUTH",
    wilaya: "Illizi Province",
    lat: 24.5542,
    lng: 9.4847,
    coords: "24°33′N · 9°29′E",
    tags: ["ROCK ART", "UNESCO", "PREHISTORY"],
    description:
      "Djanet is the gateway to Tassili n'Ajjer — over 15,000 prehistoric engravings of hunters, giraffes, and spirits on sandstone cliffs older than the Sahara desert itself.",
    art: "rockart",
    colors: ["#d4a574", "#8b4513", "#1a0f0a"],
    highlights: [
      { title: "Tassili n'Ajjer National Park", text: "UNESCO World Heritage — one of the greatest open-air prehistoric galleries on Earth." },
      { title: "Jabbaren & Sefar sites", text: "Famous panels of round-head figures, cattle, and lost-world landscapes." },
      { title: "Guided 4×4 expeditions", text: "Multi-day circuits with Tuareg guides — camping under the cliffs." },
      { title: "Djanet oasis town", text: "Palm gardens, mud-brick houses, and a relaxed desert capital." },
      { title: "Issendilen & Iherir gueltas", text: "Permanent water pools in the plateau — refuges for wildlife and nomads." },
      { title: "Rock formations", text: "Sandstone forests of arches, pillars, and labyrinthine canyons." },
      { title: "Cave paintings of the Green Sahara", text: "Images from when this land was savanna — giraffes, elephants, hippos." },
      { title: "Handicraft souq", text: "Tuareg leather, jewellery, and reproductions of rock-art motifs." },
      { title: "Tin Merzouga dune field", text: "Golden ergs at the park's edge — sandboarding and camel rides." },
      { title: "Stargazing on the plateau", text: "Camp beneath overhangs where humans painted 8,000 years ago." },
    ],
  },
  {
    city: "TLEMCEN",
    arabic: "تلمسان",
    landmark: "EL MECHOUAR",
    region: "WEST",
    wilaya: "Tlemcen Province",
    lat: 34.878,
    lng: -1.315,
    coords: "34°53′N · 1°19′W",
    tags: ["ANDALUSIAN", "PALACE", "MOSQUE"],
    description:
      "Tlemcen was once the jewel of the Maghreb — a capital of art and learning. El Mechouar citadel and the Great Mosque embody centuries of Andalusian refinement.",
    art: "palace",
    colors: ["#06d6a0", "#118ab2", "#073b4c"],
    highlights: [
      { title: "El Mechouar citadel", text: "Royal palace complex — gardens, ramparts, and views over the Tell Atlas." },
      { title: "Great Mosque of Tlemcen", text: "Almoravid masterpiece — intricate stucco, cedar ceilings, and a celebrated minbar." },
      { title: "Mansourah minaret", text: "Massive ruined tower of a 14th-century mosque — a landmark for kilometres." },
      { title: "Sidi Boumediene shrine", text: "Pilgrimage site with Andalusian tilework and a peaceful courtyard." },
      { title: "Lalla Setti plateau", text: "Forest park above the city — picnics, cafés, and panoramic sunsets." },
      { title: "Tlemcen Museum", text: "Islamic art, manuscripts, and textiles from the city's golden age." },
      { title: "Beni Snous mountains", text: "Day trips to cedar forests, waterfalls, and Berber villages." },
      { title: "Andalusian cuisine", text: "Pastilla, almond sweets, and tagines reflecting Moorish heritage." },
      { title: "Medina artisan quarter", text: "Copper, embroidery, and leather goods in centuries-old workshops." },
      { title: "Music & zianide heritage", text: "Tlemcen was a centre of Arab-Andalusian nuba classical music." },
    ],
  },
  {
    city: "BÉJAÏA",
    arabic: "بجاية",
    landmark: "YEMMA GOURAYA",
    region: "EAST",
    wilaya: "Béjaïa Province",
    lat: 36.7509,
    lng: 5.0567,
    coords: "36°45′N · 5°03′E",
    tags: ["KABYLIA", "MOUNTAIN", "BAY"],
    description:
      "Yemma Gouraya — the Sleeping Woman — guards Béjaïa bay from 660 metres. Pine forests, Kabyle villages, and a historic port meet the cerulean Mediterranean.",
    art: "mountain",
    colors: ["#48cae4", "#0096c7", "#023e8a"],
    highlights: [
      { title: "Gouraya National Park", text: "Hike to the summit for views over the bay — the mountain resembles a reclining figure." },
      { title: "Cap Carbon lighthouse", text: "One of the highest lighthouses in the Mediterranean — dramatic cliff setting." },
      { title: "Béjaïa old port & Kasbah", text: "Genoese, Spanish, and Ottoman layers in the waterfront quarter." },
      { title: "Pic des Singes (Monkey Peak)", text: "Barbary macaques in the cedar forest — rare wildlife so close to the coast." },
      { title: "Kabyle villages (Akfadou, Chemini)", text: "Mountain hamlets with walnut orchards, traditional houses, and hospitality." },
      { title: "Aokas & Les Andalouses beaches", text: "Sandy coves west of the city — swimming and beach cafés." },
      { title: "Soummam Valley", text: "Fertile hinterland of olive groves, vineyards, and market towns." },
      { title: "Yennayer (Berber New Year)", text: "If visiting in January — vibrant celebrations across Kabylia." },
      { title: "Seafood & olive oil", text: "Local anchovies, grilled fish, and some of Algeria's finest olive oil." },
      { title: "Boat trips on the bay", text: "Circle the cape from the water — cliffs, dolphins, and hidden coves." },
    ],
  },
  {
    city: "BATNA",
    arabic: "باتنة",
    landmark: "TIMGAD",
    region: "EAST",
    wilaya: "Batna Province",
    lat: 35.5559,
    lng: 6.1742,
    coords: "35°33′N · 6°10′E",
    tags: ["ROMAN", "UNESCO", "AURÈS"],
    description:
      "Batna is the gateway to Timgad — 'the Pompeii of Africa'. Emperor Trajan's grid-planned city survives intact in the Aurès Mountains, a UNESCO wonder of Roman urbanism.",
    art: "timgad",
    colors: ["#e9c46a", "#e76f51", "#264653"],
    highlights: [
      { title: "Timgad Archaeological Site", text: "UNESCO Roman city — triumphal arch, forum, library, baths, and perfect cardo/decumanus grid." },
      { title: "Trajan's Arch", text: "The iconic gateway — symbol of Timgad and one of Algeria's most photographed monuments." },
      { title: "Roman theatre", text: "Restored amphitheatre still used for summer cultural festivals." },
      { title: "Museum of Timgad", text: "Mosaics, statues, and daily-life objects from the excavations." },
      { title: "Lambaesis (Roman camp)", text: "Nearby legionary fortress — capital of Roman Numidia." },
      { title: "Aurès Mountains", text: "Berber Chaoui heartland — villages, honey, and mountain hikes." },
      { title: "Ghoufi Canyon", text: "The 'Algerian Grand Canyon' — abandoned cliff villages and dizzying views." },
      { title: "Beni Fouda hot springs", text: "Thermal baths in the mountains — popular local retreat." },
      { title: "Chaoui cuisine", text: "Berber flatbreads, mountain lamb, and wild herb teas." },
      { title: "Sunrise at the arch", text: "Arrive early — golden light on the columns before the crowds." },
    ],
  },
  {
    city: "TIMIMOUN",
    arabic: "تيميمون",
    landmark: "RED OASIS",
    region: "SAHARA",
    wilaya: "Timimoun Province",
    lat: 29.2626,
    lng: 0.2309,
    coords: "29°16′N · 0°14′E",
    tags: ["OASIS", "DUNES", "KSAR"],
    description:
      "Timimoun rises from the Gourara — the Red Oasis. Crimson mud-brick architecture, salt lakes, and golden ergs create a landscape that feels painted by the desert wind.",
    art: "oasis",
    colors: ["#e07a5f", "#f2cc8f", "#3d2c29"],
    highlights: [
      { title: "Timimoun ksar", text: "Red ochre architecture — cubic houses rising from the palm grove like a desert fortress." },
      { title: "Sebkha salt lake", text: "Mirrored flats reflecting the sky — flamingos and surreal photography." },
      { title: "Grand Erg Occidental", text: "Towering dunes on the oasis edge — camel rides and sand surfing." },
      { title: "Foggara irrigation", text: "Ancient underground channels still watering thousands of palms." },
      { title: "Beni Abbès (40 km)", text: "The 'Pearl of the Saoura' — Charles de Foucauld chapel and Saoura valley." },
      { title: "Gourara villages circuit", text: "Tinerkouk, Ouled Saïd — each oasis with its own ksar and market day." },
      { title: "Desert sunsets", text: "The red buildings absorb the last light — the oasis glows like embers." },
      { title: "Dates & desert bread", text: "Deglet nour, khobz el dar, and sweet mint tea in every guesthouse." },
      { title: "Star camps", text: "Luxury and basic bivouacs on the dunes — silence and stars." },
      { title: "4×4 to salt flats", text: "Cross the sebkha at dawn when the surface still holds reflections." },
    ],
  },
  {
    city: "ANNABA",
    arabic: "عنابة",
    landmark: "BASILICA OF AUGUSTINE",
    region: "EAST",
    wilaya: "Annaba Province",
    lat: 36.9,
    lng: 7.7667,
    coords: "36°54′N · 7°46′E",
    tags: ["BASILICA", "HIPPO", "COAST"],
    description:
      "Annaba overlooks ancient Hippo Regius, where Saint Augustine once preached. The basilica crowns a hill above one of Algeria's finest ports on the eastern Mediterranean.",
    art: "basilica",
    colors: ["#b8c0ff", "#6c63ff", "#1a1a2e"],
    highlights: [
      { title: "Basilica of St. Augustine", text: "Byzantine-revival cathedral on the hill — mosaics, crypt, and sea panoramas." },
      { title: "Hippo Regius ruins", text: "Roman forum, baths, and Christian basilica where Augustine was bishop." },
      { title: "Hippo Museum", text: "Mosaics, Punic stelae, and exhibits on Augustine's life and theology." },
      { title: "Annaba corniche", text: "Palm-lined waterfront promenade — cafés, beaches, and evening crowds." },
      { title: "Seraïdi mountain resort", text: "Cool pine forests above the city — summer escape and hiking trails." },
      { title: "Edough National Park", text: "Forested massif — waterfalls, wild boar, and mountain villages." },
      { title: "Port & steel city heritage", text: "Industrial history alongside ancient ruins — a city of contrasts." },
      { title: "Sidi Boumerouane beach", text: "Popular swimming spot east of the centre." },
      { title: "Fresh fish market", text: "Morning auction at the port — sardines, sea bream, and calamari." },
      { title: "Augustine pilgrimage route", text: "Walk in the footsteps of one of Christianity's greatest thinkers." },
    ],
  },
];
